version: '3.7'
services:
  neo4jngs:
    image: neo4j:4.4.8-enterprise
    restart: always
    hostname: neo4jngs
    container_name: neo4jngs
    ports:
      - 21212:7474
      - 22333:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/backup:/backup
      - ./neo4j/plugins:/plugins
      - ./neo4j/conf:/conf
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/ngslbd2020
      - NEO4J_dbms_connector_bolt_advertised__address=194.249.1.168:22333
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_transaction_timeout=20s
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_default__database=semmed432202
      - NEO4J_dbms_allow__upgrade=true
  api:
    build:
      context: ./API
    hostname: api
    restart: always
    container_name: api
    ports:
      - 64000:3000
    depends_on:
        - neo4jngs
  graphql:
    build:
      context: ./graphQL
    hostname: graphQL
    restart: always
    container_name: graphQL
    environment:
      - DEBUG=neo4j-graphql-js
    ports:
      - 64001:4001
    depends_on:
        - neo4jngs
  client:
    build: ./client
    ports:
      - 64002:3000
    environment:
      - REACT_APP_GRAPHQL_URI=http://api:4001/graphql
    links:
      - graphql
    depends_on:
      - graphql
  pykeen:
    build: ./pykeenClient
    ports:
     - 64003:3000    
