version: '3.7'
services:
  neo4jngs:
    image: neo4j:4.1.2-enterprise
    restart: always
    hostname: neo4jngs
    container_name: neo4jngs
    ports:
      - 21212:7474
      - 22333:7687
    volumes:
      - /home/gbergant/ngslbd/neo4j/data:/data
      - /home/gbergant/ngslbd/neo4j/import:/import
      - /home/gbergant/ngslbd/neo4j/backup/:/backup
      - /home/gbergant/ngslbd/neo4j/plugins:/plugins
      - /home/gbergant/ngslbd/neo4j/conf:/conf
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/ngslbd2020
      - NEO4J_dbms_connector_bolt_advertised__address=10.10.9.11:22333
      - NEO4JLABS_PLUGINS=["apoc"]
#      - NEO4J_dbms_transaction_timeout=300s
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
  api:
    build:
      context: ./API
    hostname: api
    restart: always
    container_name: api
    ports:
      - 64000:3001
    depends_on:
        - neo4jngs
  graphql:
    build:
      context: ./graphQL
    hostname: graphQL
    restart: always
    container_name: graphQL
    ports:
      - 64001:4001
    depends_on:
        - neo4jngs
  client:
    build: ./client
    ports:
      - 64002:3001
    environment:
      - REACT_APP_GRAPHQL_URI=http://api:4001/graphql
    links:
      - graphql
    depends_on:
      - graphql
  pykeen:
    build: ./pykeenClient
    ports:
     - 64003:3000    
  
